"""Alembic: migrations apply cleanly, match the ORM models, and downgrade."""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect

from claimpilot.config import API_ROOT


@pytest.fixture
def db(tmp_path: Path) -> tuple[Config, str]:
    path = (tmp_path / "m.db").as_posix()
    config = Config(API_ROOT / "alembic.ini")
    config.attributes["database_url"] = f"sqlite+aiosqlite:///{path}"
    config.attributes["configure_logger"] = False
    return config, f"sqlite:///{path}"


def tables(sync_url: str) -> set[str]:
    engine = create_engine(sync_url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_creates_llm_calls_and_matches_models(db):
    config, sync_url = db
    command.upgrade(config, "head")
    assert "llm_calls" in tables(sync_url)
    try:
        command.check(config)  # autogenerate finds no drift between models and migrations
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure message only
        pytest.fail(f"models and migrations differ: {exc}")


def test_downgrade_removes_everything(db):
    config, sync_url = db
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    assert tables(sync_url) <= {"alembic_version"}
