"""Metadata forensics: what the file itself says about where it came from.

Genuine receipts are photographed, scanned, screenshotted or generated by billing software.
Forged ones are often edited in a photo editor or an online PDF editor, or drawn by an image
generator, and most of those tools leave a trace in the file's metadata. This module reads that
trace; it does not look at pixels (no error-level analysis), so it is cheap and rarely wrong.

=========================  ========  ====================================================
code                       severity  fires when
=========================  ========  ====================================================
``edited_software``        warn      EXIF Software / ProcessingSoftware, XMP CreatorTool or
                                     softwareAgent, a PNG text chunk or the JPEG comment
                                     names an image editor (Photoshop, GIMP, Canva, ...)
``pdf_editor_producer``    warn      a PDF's /Producer or /Creator (or XMP) names a PDF
                                     editor or an online "edit PDF" service
``ai_generated_metadata``  high      PNG/EXIF/XMP metadata names an image generator or carries
                                     its settings (Stable Diffusion "parameters", IPTC digital
                                     source type "trained algorithmic media", ...)
``exif_date_mismatch``     info/warn the camera date is in the future (warn), or long after the
                                     date printed on the bill (info after 60 days, warn after
                                     180)
``file_type_mismatch``     info      the file extension disagrees with the actual file type
=========================  ========  ====================================================

What is deliberately NOT flagged: a missing camera make/model or any missing metadata (screenshots,
scans and messaging apps strip it), scanner apps (Adobe Scan, CamScanner), phone camera software
strings, and ordinary PDF producers (Chromium/Skia, Word, LibreOffice, wkhtmltopdf, ReportLab).

Findings never echo raw metadata: a "Software" string is attacker-controlled, and findings are
read by people and by the chat agent. Messages name only the tool *we* recognised (a fixed
label), never the file's own text.

Limits: metadata is trivially stripped, so a clean result proves nothing; only a hit is evidence.
PDFs are read by scanning the file for /Producer and /Creator strings and the XMP packet rather
than through a PDF library, which keeps pdfium (not thread-safe) out of this check; an Info
dictionary stored in a compressed object stream is missed unless the XMP repeats it.
"""

from __future__ import annotations

import contextlib
import io
import re
import zlib
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Any, Final, Literal

from PIL import Image

from claimpilot.domain import ExtractedReceipt
from claimpilot.domain.findings import Finding, Severity

FileKind = Literal["jpeg", "png", "webp", "pdf"]

EXIF_LATE_INFO_DAYS: Final = 60  # photo taken this long after the printed date: worth a note
EXIF_LATE_WARN_DAYS: Final = 180  # ... and this long: needs a look
EXIF_FUTURE_TOLERANCE_DAYS: Final = 1  # time zones and a camera clock a few hours ahead

MAX_XMP_PACKETS: Final = 4
MAX_XMP_CHARS: Final = 262_144
MAX_PNG_CHUNKS: Final = 2_000
MAX_PNG_TEXT_BYTES: Final = 1_048_576
MAX_PDF_KEYS: Final = 64
MAX_TOOL_CHARS: Final = 2_000  # tool-name fields are short; ignore the tail of a long text


def _table(rows: tuple[tuple[str, str], ...]) -> tuple[tuple[str, re.Pattern[str]], ...]:
    return tuple((label, re.compile(pattern, re.IGNORECASE)) for label, pattern in rows)


IMAGE_EDITORS: Final = _table(
    (
        ("Adobe Photoshop", r"photoshop"),
        ("Adobe Lightroom", r"lightroom"),
        ("GIMP", r"\bgimp\b"),
        ("Canva", r"\bcanva\b"),
        ("Snapseed", r"snapseed"),
        ("Pixelmator", r"pixelmator"),
        ("Affinity", r"\baffinity\b"),
        ("Paint.NET", r"paint\.net"),
        ("Photopea", r"photopea"),
        ("Pixlr", r"pixlr"),
        ("PicsArt", r"picsart"),
        ("Fotor", r"\bfotor\b"),
        ("PhotoScape", r"photoscape"),
        ("PaintShop Pro", r"paintshop"),
        ("Krita", r"\bkrita\b"),
        ("Adobe Illustrator", r"illustrator"),
        ("Inkscape", r"inkscape"),
        ("Figma", r"\bfigma\b"),
        ("Facetune", r"facetune"),
        ("a photo editor", r"\b(?:photo|image)\s*editor\b"),
        ("an editing app", r"\bedited\s+(?:with|by|in|using)\b"),
    )
)

PDF_EDITORS: Final = _table(
    (
        ("Sejda", r"sejda"),
        ("iLovePDF", r"ilovepdf"),
        ("Smallpdf", r"smallpdf"),
        ("PDFescape", r"pdfescape"),
        ("pdfFiller", r"pdffiller"),
        ("DocHub", r"dochub"),
        ("PDF Candy", r"pdf\s*candy"),
        ("Soda PDF", r"soda\s*pdf"),
        ("PDF-XChange Editor", r"pdf[\s-]*xchange\s*editor"),
        ("Foxit PDF Editor", r"foxit.{0,20}(?:editor|phantom)"),
        ("Nitro PDF", r"\bnitro\b"),
        ("PDFelement", r"pdfelement"),
        ("Xodo", r"\bxodo\b"),
        ("Lumin PDF", r"lumin\s*pdf"),
        ("PDFgear", r"pdfgear"),
        ("a PDF editor", r"\bpdf\s*editor\b|\bedit\s*pdf\b"),
        ("Adobe Photoshop", r"photoshop"),
        ("Adobe Illustrator", r"illustrator"),
        ("Canva", r"\bcanva\b"),
        ("Inkscape", r"inkscape"),
        ("GIMP", r"\bgimp\b"),
        ("Affinity", r"\baffinity\b"),
        ("an editing app", r"\bedited\s+(?:with|by|in|using)\b"),
    )
)

# Names of image generators. Matched only against tool-like fields (Software, CreatorTool,
# Producer, PNG text, JPEG comment, EXIF UserComment/ImageDescription), never the whole file.
AI_GENERATORS: Final = _table(
    (
        (
            "Stable Diffusion",
            r"stable[\s_-]*diffusion|\bsdxl\b|automatic1111|comfy\s*ui|invoke\s*ai",
        ),
        ("NovelAI", r"novel\s*ai"),
        ("Midjourney", r"midjourney"),
        ("DALL-E", r"\bdall[^a-z0-9]{0,3}e\b"),  # DALL-E, DALL·E, dall e, dalle
        # "Firefly", "Imagen" and "Gemini" alone are ordinary words and shop names: qualified only
        ("Adobe Firefly", r"adobe\s*firefly"),
        ("Google Imagen / Gemini", r"google\s+(?:imagen|gemini)|\b(?:imagen|gemini)[\s-]*\d"),
        ("ChatGPT / OpenAI", r"chatgpt|openai|\bgpt[\s-]*(?:4o|image)"),
        ("Ideogram", r"ideogram"),
        ("Leonardo.Ai", r"leonardo[\s.]*ai"),
        ("Bing Image Creator", r"bing\s*image\s*creator"),
        ("Black Forest Labs", r"black\s*forest\s*labs"),
        (
            "an AI image generator",
            r"\bai[\s-]*generated\b|generated\s+(?:by|with|using)\s+(?:an?\s+)?(?:ai|artificial)"
            r"|\bsynthid\b|made\s+with\s+google\s+ai",
        ),
    )
)

# The IPTC "digital source type" values that mean "made by a generative model" (fully, or by
# compositing generated content into a real picture).
_AI_SOURCE_TYPE: Final = re.compile(
    r"digitalsourcetype/(?:trainedAlgorithmicMedia|compositeWithTrainedAlgorithmicMedia)",
    re.IGNORECASE,
)
_AI_IPTC_PROPERTY: Final = re.compile(
    r"Iptc4xmpExt:(?:AISystemUsed|AISystemVersionUsed|AIPromptInformation|AIPromptWriterName)",
    re.IGNORECASE,
)
_SD_PARAMETERS: Final = re.compile(
    r"\bSteps:\s*\d+.{0,400}?\b(?:Sampler|CFG scale|Seed):", re.DOTALL
)
_COMFY_GRAPH: Final = re.compile(r'"class_type"\s*:')
_SD_PNG_KEYS: Final = frozenset({"sd-metadata", "invokeai_metadata", "invokeai_graph", "dream"})
_PNG_TOOL_KEYS: Final = frozenset(
    {"software", "comment", "source", "description", "creator", "producer", "generator"}
)

_XMP_OPEN: Final = b"<x:xmpmeta"
_XMP_CLOSE: Final = b"</x:xmpmeta>"
_XMP_TOOL: Final = re.compile(
    r"(?:CreatorTool|softwareAgent|Producer)\s*=\s*\"([^\"]{1,200})\""
    r"|<(?:\w+:)?(?:CreatorTool|softwareAgent|Producer)\b[^>]*>([^<]{1,200})<",
    re.IGNORECASE,
)

_EXIF_SOFTWARE: Final = 0x0131
_EXIF_PROCESSING_SOFTWARE: Final = 0x000B
_EXIF_IMAGE_DESCRIPTION: Final = 0x010E
_EXIF_DATETIME: Final = 0x0132
_EXIF_IFD_POINTER: Final = 0x8769
_EXIF_DATETIME_ORIGINAL: Final = 0x9003
_EXIF_DATETIME_DIGITIZED: Final = 0x9004
_EXIF_USER_COMMENT: Final = 0x9286
_EXIF_DATE: Final = re.compile(r"(\d{4})[:/-](\d{2})[:/-](\d{2})")

_EXTENSION_TYPES: Final = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
    ".pdf": "application/pdf",
}
_TYPE_NAMES: Final = {
    "image/jpeg": "a JPEG image",
    "image/png": "a PNG image",
    "image/webp": "a WebP image",
    "application/pdf": "a PDF",
}


@dataclass(frozen=True, slots=True)
class FileMetadata:
    """What forensics could read. ``tools`` holds raw strings and must never reach a message."""

    kind: FileKind | None = None
    tools: tuple[str, ...] = ()  # Software / CreatorTool / Producer ... as found in the file
    ai_markers: tuple[str, ...] = ()  # fixed labels, safe to show
    captured: date | None = None  # EXIF capture date


def sniff_kind(raw: bytes) -> FileKind | None:
    if raw.startswith(b"\xff\xd8\xff"):
        return "jpeg"
    if raw.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"
    if raw[:4] == b"RIFF" and raw[8:12] == b"WEBP":
        return "webp"
    if raw.startswith(b"%PDF-"):
        return "pdf"
    return None


# --- reading --------------------------------------------------------------------------------


def read_metadata(raw: bytes) -> FileMetadata:
    """Collect tool names, AI markers and the capture date. Never raises on hostile input."""
    kind = sniff_kind(raw)
    if kind is None:
        return FileMetadata()
    tools: list[str] = []
    ai: list[str] = []

    packets = _xmp_packets(raw)
    for packet in packets:
        tools += [m[0] or m[1] for m in _XMP_TOOL.findall(packet)]
        if _AI_SOURCE_TYPE.search(packet):
            ai.append("IPTC digital source type: made by a generative AI model")
        if _AI_IPTC_PROPERTY.search(packet):
            ai.append("IPTC AI system / prompt fields")

    captured: date | None = None
    if kind == "pdf":
        tools += _pdf_strings(raw)
    else:
        exif_payload: bytes | None = None
        if kind == "png":
            texts, exif_payload = _png_metadata(raw)
            for key, value in texts.items():
                ai += _png_ai_markers(key, value)
                if key.lower() in _PNG_TOOL_KEYS:
                    tools.append(value[:MAX_TOOL_CHARS])
        exif, comment = _read_exif(raw, kind, exif_payload)
        if comment:
            tools.append(comment)
        if exif is not None:
            tools += _exif_tools(exif)
            ai += _exif_ai_markers(exif)
            captured = _exif_capture_date(exif)

    ai += [label for label in (_ai_label(t) for t in tools) if label]
    return FileMetadata(
        kind=kind,
        tools=tuple(dict.fromkeys(t for t in tools if t)),
        ai_markers=tuple(dict.fromkeys(ai)),
        captured=captured,
    )


def _xmp_packets(raw: bytes) -> list[str]:
    """XMP packets (JPEG APP1, PNG iTXt, WebP, PDF metadata), found with plain searches."""
    packets: list[str] = []
    position = 0
    while len(packets) < MAX_XMP_PACKETS:
        start = raw.find(_XMP_OPEN, position)
        if start < 0:
            break
        end = raw.find(_XMP_CLOSE, start)
        if end < 0:
            break  # an unclosed packet: nothing after it can close either
        packets.append(raw[start:end][:MAX_XMP_CHARS].decode("utf-8", errors="replace"))
        position = end + len(_XMP_CLOSE)
    return packets


def _read_exif(
    raw: bytes, kind: FileKind, payload: bytes | None
) -> tuple[Image.Exif | None, str | None]:
    """(EXIF, JPEG comment). PNG EXIF comes from the eXIf chunk so the pixels are never decoded."""
    try:
        if kind == "png":
            if payload is None:
                return None, None
            exif = Image.Exif()
            exif.load(payload)
            return exif, None
        with Image.open(io.BytesIO(raw)) as image:
            comment = image.info.get("comment")
            text = comment.decode("utf-8", errors="replace") if isinstance(comment, bytes) else None
            return image.getexif(), text
    except (OSError, ValueError, SyntaxError, TypeError, KeyError, Image.DecompressionBombError):
        return None, None


def _exif_text(value: object) -> str:
    if isinstance(value, bytes):
        if value[:8] in (b"ASCII\x00\x00\x00", b"UNICODE\x00", b"JIS\x00\x00\x00\x00\x00"):
            codec = "utf-16-be" if value[:8] == b"UNICODE\x00" else "ascii"
            return value[8:].decode(codec, errors="replace").strip("\x00 ")
        return value.decode("utf-8", errors="replace").strip("\x00 ")
    return str(value).strip("\x00 ") if value is not None else ""


def _exif_tools(exif: Image.Exif) -> list[str]:
    values = [exif.get(_EXIF_SOFTWARE), exif.get(_EXIF_PROCESSING_SOFTWARE)]
    return [text for text in (_exif_text(v) for v in values) if text]


def _exif_ifd(exif: Image.Exif) -> dict[int, Any]:
    """The Exif sub-IFD (capture dates, UserComment); empty when absent or damaged."""
    try:
        return dict(exif.get_ifd(_EXIF_IFD_POINTER))
    except (KeyError, ValueError, TypeError, SyntaxError, OSError):
        return {}


def _exif_ai_markers(exif: Image.Exif) -> list[str]:
    markers: list[str] = []
    texts = [
        _exif_text(exif.get(_EXIF_IMAGE_DESCRIPTION)),
        _exif_text(_exif_ifd(exif).get(_EXIF_USER_COMMENT)),
    ]
    for text in texts:
        if text and _SD_PARAMETERS.search(text):
            markers.append("Stable Diffusion settings in the image metadata")
        if label := _ai_label(text):
            markers.append(label)
    return markers


def _exif_capture_date(exif: Image.Exif) -> date | None:
    sub = _exif_ifd(exif)
    candidates: list[object] = [
        sub.get(_EXIF_DATETIME_ORIGINAL),
        sub.get(_EXIF_DATETIME_DIGITIZED),
        exif.get(_EXIF_DATETIME),
    ]
    for candidate in candidates:
        match = _EXIF_DATE.match(_exif_text(candidate))
        if match is None:
            continue
        try:
            return date(int(match[1]), int(match[2]), int(match[3]))
        except ValueError:
            continue  # "0000:00:00 00:00:00" and friends: no usable date
    return None


def _ai_label(text: str) -> str | None:
    """A fixed label if ``text`` (a tool-name-like field) names an image generator."""
    head = text[:MAX_TOOL_CHARS]
    for label, pattern in AI_GENERATORS:
        if pattern.search(head):
            return f"{label} named in the file's metadata"
    return None


# --- PNG ------------------------------------------------------------------------------------


def _inflate(data: bytes) -> bytes:
    try:
        return zlib.decompressobj().decompress(data, MAX_PNG_TEXT_BYTES)
    except zlib.error:
        return b""


def _png_metadata(raw: bytes) -> tuple[dict[str, str], bytes | None]:
    """Text chunks (tEXt, zTXt, iTXt) and the eXIf payload, walked chunk by chunk."""
    texts: dict[str, str] = {}
    exif: bytes | None = None
    position = 8
    for _ in range(MAX_PNG_CHUNKS):
        if position + 8 > len(raw):
            break
        length = int.from_bytes(raw[position : position + 4], "big")
        kind = raw[position + 4 : position + 8]
        data = raw[position + 8 : position + 8 + length]
        position += 12 + length
        if kind == b"IEND":
            break
        if kind == b"eXIf":
            exif = data
        elif kind in (b"tEXt", b"zTXt", b"iTXt"):
            key, _, rest = data.partition(b"\x00")
            texts[key.decode("latin-1")[:80]] = _png_text_value(kind, rest)
    return texts, exif


def _png_text_value(kind: bytes, rest: bytes) -> str:
    if kind == b"tEXt":
        return rest[:MAX_PNG_TEXT_BYTES].decode("latin-1")
    if kind == b"zTXt":
        return _inflate(rest[1:]).decode("latin-1")  # rest[0] is the compression method
    flag = rest[:1]
    body = rest[2:]  # skip compression flag + method
    _language, _, body = body.partition(b"\x00")
    _translated, _, text = body.partition(b"\x00")
    if flag == b"\x01":
        text = _inflate(text)
    return text[:MAX_PNG_TEXT_BYTES].decode("utf-8", errors="replace")


def _png_ai_markers(key: str, value: str) -> list[str]:
    name = key.lower()
    markers: list[str] = []
    if name in _SD_PNG_KEYS or (name == "parameters" and _SD_PARAMETERS.search(value)):
        markers.append("Stable Diffusion settings in the PNG metadata")
    elif (name == "prompt" and _COMFY_GRAPH.search(value)) or (
        name == "workflow" and '"nodes"' in value
    ):
        markers.append("ComfyUI workflow in the PNG metadata")
    return markers


# --- PDF ------------------------------------------------------------------------------------

_PDF_ESCAPES: Final = {
    ord("n"): "\n",
    ord("r"): "\r",
    ord("t"): "\t",
    ord("b"): "\b",
    ord("f"): "\f",
}


def _pdf_literal(raw: bytes, start: int) -> tuple[bytes, int]:
    """Parse the literal string whose ``(`` is at ``start``: balanced parentheses and escapes."""
    out = bytearray()
    depth = 0
    i = start
    end = min(len(raw), start + 4096)
    while i < end:
        byte = raw[i]
        if byte == 0x5C and i + 1 < end:  # backslash
            nxt = raw[i + 1]
            if 0x30 <= nxt <= 0x37:  # octal escape, up to three digits
                j = i + 1
                digits = b""
                while j < end and len(digits) < 3 and 0x30 <= raw[j] <= 0x37:
                    digits += raw[j : j + 1]
                    j += 1
                out.append(int(digits, 8) & 0xFF)
                i = j
                continue
            out += _PDF_ESCAPES.get(nxt, chr(nxt)).encode("latin-1", errors="replace")
            i += 2
            continue
        if byte == 0x28:
            depth += 1
            if depth > 1:
                out.append(byte)
        elif byte == 0x29:
            depth -= 1
            if depth == 0:
                return bytes(out), i + 1
            out.append(byte)
        else:
            out.append(byte)
        i += 1
    return bytes(out), end


def _pdf_text(data: bytes) -> str:
    if data.startswith(b"\xfe\xff"):
        return data[2:].decode("utf-16-be", errors="replace")
    if data.startswith(b"\xff\xfe"):
        return data[2:].decode("utf-16-le", errors="replace")
    if data.startswith(b"\xef\xbb\xbf"):
        return data[3:].decode("utf-8", errors="replace")
    return data.decode("latin-1")


def _pdf_strings(raw: bytes) -> list[str]:
    """Every /Producer and /Creator string in the file (incremental updates keep old ones)."""
    found: list[str] = []
    for key in (b"/Producer", b"/Creator"):
        position = 0
        for _ in range(MAX_PDF_KEYS):
            position = raw.find(key, position)
            if position < 0:
                break
            position += len(key)
            if raw[position : position + 1].isalnum():  # /CreatorXYZ, not /Creator
                continue
            while position < len(raw) and raw[position : position + 1] in b" \t\r\n":
                position += 1
            if raw[position : position + 1] == b"(":
                data, position = _pdf_literal(raw, position)
                found.append(_pdf_text(data))
            elif raw[position : position + 1] == b"<" and raw[position + 1 : position + 2] != b"<":
                close = raw.find(b">", position, position + 8192)
                if close > 0:
                    digits = re.sub(rb"\s+", b"", raw[position + 1 : close])
                    with contextlib.suppress(ValueError):  # odd length or not hexadecimal
                        found.append(_pdf_text(bytes.fromhex(digits.decode("ascii"))))
    return [text.strip("\x00 ") for text in found if text.strip("\x00 ")]


# --- findings -------------------------------------------------------------------------------


_GENERIC_LABELS: Final = frozenset({"a photo editor", "an editing app", "a PDF editor"})


def _labels(tools: tuple[str, ...], table: tuple[tuple[str, re.Pattern[str]], ...]) -> list[str]:
    """Editor labels found in the tool strings; a generic label only when nothing named it."""
    labels: list[str] = []
    for tool in tools:
        found = [label for label, pattern in table if pattern.search(tool)]
        specific = [label for label in found if label not in _GENERIC_LABELS]
        labels += specific or found
    return list(dict.fromkeys(labels))


def _join(labels: list[str]) -> str:
    return ", ".join(labels[:-1]) + f" and {labels[-1]}" if len(labels) > 1 else labels[0]


def metadata_findings(
    raw: bytes, receipt: ExtractedReceipt | None = None, *, today: date | None = None
) -> list[Finding]:
    """Run every metadata rule on the original upload bytes.

    ``receipt`` supplies the printed date for the capture-date comparison; ``today`` is for tests.
    """
    meta = read_metadata(raw)
    findings: list[Finding] = []

    if meta.ai_markers:
        findings.append(
            Finding(
                code="ai_generated_metadata",
                severity=Severity.high,
                message="The file's metadata shows it was produced by an AI image generator "
                f"({meta.ai_markers[0]}); a real bill is not generated.",
                actual=meta.ai_markers[0],
            )
        )

    if meta.kind == "pdf":
        editors = _labels(meta.tools, PDF_EDITORS)
        if editors:
            findings.append(
                Finding(
                    code="pdf_editor_producer",
                    severity=Severity.warn,
                    message=f"The PDF was last written by {_join(editors)}, a tool for editing "
                    "documents rather than the billing system that issued it.",
                    actual=editors[0],
                )
            )
    elif meta.kind is not None:
        editors = _labels(meta.tools, IMAGE_EDITORS)
        if editors:
            findings.append(
                Finding(
                    code="edited_software",
                    severity=Severity.warn,
                    message=f"The image's metadata says it was processed with {_join(editors)}, "
                    "so it may have been edited after it was captured.",
                    actual=editors[0],
                )
            )

    findings += _capture_date_findings(meta.captured, receipt, today or date.today())
    return findings


def _capture_date_findings(
    captured: date | None, receipt: ExtractedReceipt | None, today: date
) -> list[Finding]:
    if captured is None:
        return []
    if captured > today + timedelta(days=EXIF_FUTURE_TOLERANCE_DAYS):
        return [
            Finding(
                code="exif_date_mismatch",
                severity=Severity.warn,
                message=f"The photo's capture date ({captured:%d %b %Y}) is in the future, so "
                "the camera clock or the file's metadata is wrong.",
                fields=("date",),
                expected=f"on or before {today.isoformat()}",
                actual=captured.isoformat(),
            )
        ]
    printed = _printed_date(receipt)
    if printed is None:
        return []
    days = (captured - printed).days
    if days <= EXIF_LATE_INFO_DAYS:
        return []
    return [
        Finding(
            code="exif_date_mismatch",
            severity=Severity.warn if days > EXIF_LATE_WARN_DAYS else Severity.info,
            message=f"The photo was taken on {captured:%d %b %Y}, {days} days after the date "
            f"printed on the bill ({printed:%d %b %Y}).",
            fields=("date",),
            expected=printed.isoformat(),
            actual=captured.isoformat(),
        )
    ]


def _printed_date(receipt: ExtractedReceipt | None) -> date | None:
    if receipt is None or not receipt.date:
        return None
    try:
        return date.fromisoformat(receipt.date.strip())
    except ValueError:
        return None


def check_file_type(filename: str, media_type: str) -> list[Finding]:
    """``file_type_mismatch`` (info) when the extension names a different type than the content."""
    dot = filename.rfind(".")
    declared = _EXTENSION_TYPES.get(filename[dot:].lower()) if dot >= 0 else None
    if declared is None or declared == media_type:
        return []
    return [
        Finding(
            code="file_type_mismatch",
            severity=Severity.info,
            message=f"The file's name suggests {_TYPE_NAMES[declared]} but it is actually "
            f"{_TYPE_NAMES.get(media_type, media_type)}.",
            expected=declared,
            actual=media_type,
        )
    ]
